Repository Automattic/ElasticPress, pull requests merged in 2020-03, with the labels that each got.

#7 Add missing semi-colon
  includes/classes/Indexable/Post/Post.php
Labels: [Status] Needs Review

#8 Add scripts for phpunit with docker
  bin/download-wp-tests.sh
  bin/phpunit-docker.sh
Labels: [Status] Needs Review

#9 Add invalid Elasticsearch response action
  includes/classes/Elasticsearch.php
Labels: [Status] Needs Review

#12 Add multi get functions
  includes/classes/Elasticsearch.php
  includes/classes/Indexable.php
Labels: [Status] Has Feedback

#14 Merge develop into master( for #13 )
  includes/classes/Elasticsearch.php
  includes/classes/Indexable.php
  includes/classes/Indexable/Post/Post.php
Labels: [Status] Ready to Deploy

#15 Allow query integration during indexing with a filter
  includes/classes/Indexable/Post/QueryIntegration.php
  includes/classes/Indexable/Term/QueryIntegration.php
  includes/classes/Indexable/User/QueryIntegration.php
Labels: [Status] Ready to Deploy

#18 Un-queue trashed posts
  includes/classes/Indexable/Post/SyncManager.php
  includes/classes/SyncManager.php
  tests/php/includes/classes/TestSyncManager.php
  tests/php/indexables/TestPost.php
Labels: [Status] Ready to Deploy

#21 Check post status before re-indexing after term changes
  includes/classes/Indexable/Post/SyncManager.php
Labels: [Status] Ready to Deploy

#22 Added ep_facet_taxonomies_size filter
  includes/classes/Feature/Facets/Facets.php
Labels: [Status] Ready to Deploy

#20 Move permission bypass checks to filters
  tests/php/includes/classes/Indexables/Post/SyncManager.php
  tests/php/indexables/Post/SyncManager.php
Labels: [Status] Ready to Deploy
