Repository Automattic/ElasticPress, pull requests merged in 2021-11, with the labels that each got.

#123 Search feature: account for multisite in is_synonym_page()
  includes/classes/Feature/Search/Synonyms.php
Labels: [Status] Needs Review

#126 Bump EP_ES_VERSION_MAX to 7.10.2
  elasticpress.php
Labels: [Status] Ready to Deploy

#125 Fix 299 Specifying types in multi get requests is deprecated warning
  includes/classes/Elasticsearch.php
Labels: [Status] Ready to Deploy

#119 Fix incorrect invocation of is_callable()
  includes/classes/Command.php
Labels: [Status] Ready to Deploy

#127 Add "VIP: " comments for VIP-specific changes
  elasticpress.php
  includes/classes/Command.php
  includes/classes/Feature/Facets/Widget.php
  includes/classes/Feature/Search/Synonyms.php
  includes/classes/Indexable.php
  includes/classes/Indexable/Post/Post.php
  includes/classes/Indexable/Post/QueryIntegration.php
  includes/utils.php
  tests/php/TestUtils.php
  tests/php/indexables/TestPost.php
Labels: [Status] Needs Review

#124 Load admin styles for Search feature pages of subsites in multisite instance
  includes/classes/Screen.php
  tests/php/TestScreen.php
Labels: [Status] Needs Review

#130 Account for offset in result window limitation
  includes/classes/Indexable.php
  includes/classes/Indexable/Comment/Comment.php
Labels: [Status] Needs Review, [Status] Upstream fix

#131 Add $type to ep_do_intercept_request filter
  includes/classes/Elasticsearch.php
Labels: [Status] Ready to Deploy, [Status] Upstream fix

#133 drop custom taxonomies exclusion
  includes/classes/Indexable/Post/Post.php
Labels: [Status] Needs Review

#134 Return back admin notice for incorrect mapping version
  includes/classes/AdminNotices.php
Labels: [Status] Needs Review
